### ISSUE TITLE
Request: for onError, also provide the onActivityResult parameters, to investigate the errors if needed

### ISSUE THREAD

**Issue by AndroidDeveloperLB** [hendraanggrian/dispatcher#3]
Currently it just has Throwable ...

**Comment by hanggrian** [comment]
I have not yet investigate the other issue you have opened, but I can speak for this one. That Throwable is the default behavior of RxJava when onError is called. If it is indeed an error caused by this library, that Throwable is most likely to be an ActivityResultException. In that case, you may obtain the result code by casting that Throwable into ActivityResultException.

I may provide more of onActivityResult into ActivityResultException to investigate error, but I will not change the default behavior of RxJava.

**Comment by AndroidDeveloperLB** [comment]
I see. OK. Add the missing information there then. The requestCode is less useful, because we already don't use it with this library...

Thank you.
The other issue is actually more important to us.

**Comment by hanggrian** [comment]
Yes, that is actually one of the main reasons that motivates me the most about this library: not having to deal with request code.

Anyway, `ActiviyResultException` of version 0.9 should contain all of `onActivityResult()`'s parameters. Thank you for pointing this out and let me know if you have any other issues.

**Comment by AndroidDeveloperLB** [comment]
Thank you!
